---
- name: Update apt repository
  apt:
    update_cache: yes 

- name: Add PHP repo
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: add nginx public key
  apt_key: 
    keyserver: keyserver.ubuntu.com
    id: ABF5BD827BD9BF62

- name: append repo in source.list
  ansible.builtin.apt_repository:
    repo: deb-src https://nginx.org/packages/ubuntu/ {{ ubuntu_release }} nginx
    state: present

- name: Update apt repository
  apt:
    update_cache: yes 

- name: install packages on ubuntu
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - build-essential
  - git
  - nginx
  - php8.0
  - php8.0-fpm
  - sqlite3
  - php8.0-sqlite3
  - npm
  - secure-delete
  - nodejs
  - certbot
  - make
...
