---
- name: Update apt repository
  apt:
    update_cache: yes 

- name: Add PHP repo
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: add nginx public key
  apt_key: 
    keyserver: keyserver.ubuntu.com
    id: ABF5BD827BD9BF62

- name: get nginx repo link
  shell: echo deb-src https://nginx.org/packages/ubuntu/ $(lsb_release -cs) nginx
  register: repo_link

- name: append repo into source.list
  ansible.builtin.apt_repository:
    repo: "{{repo_link.stdout}}"
    state: present

- name: Update apt repository
  apt:
    update_cache: yes 

- name: install packages on ubuntu
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - build-essential
  - git
  - nginx-full
  - php8.0
  - php8.0-fpm
  # - php8.0--xml
  - zip
  - sqlite3
  - php8.0-sqlite3
  - secure-delete
  - certbot
  - make
...
