---
- uri:
    url: https://api.github.com/repos/nokonoko/Uguu/releases/latest
    return_content: true
  register: json_reponse

- name: clone latest version of uguu repository
  git:
    repo: https://github.com/nokonoko/uguu
    dest: /var/www/uguu
    version: "{{ json_reponse.json.tag_name }}"
    force: yes
    clone: yes

- name: make working directorys
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
  - /var/www
  - /var/www/uguu
  - /var/www/uguu/dist
  - /var/www/db
  - /var/www/files

- name: init the sqlitedb
  shell: cd /var/www/uguu/ && sqlite3 uguu.sq3 -init /var/www/uguu/src/static/dbSchemas/sqlite_schema.sql ""
  async: 30
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
  
- name: change directory ownership
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  with_items:
  - /var/www/db
  - /var/www/files
  
- name: change directory permission
  file:
    path: "{{ item }}"
    mode: '0775'
    state: directory
    recurse: yes
  with_items:
  - /var/www
  - /var/www/
  
- name: change files mode to execute
  file:
    path: "{{ item }}"
    mode: '0775'
    state: file
    force: yes
  with_items:
  - /var/www/uguu/src/static/scripts/checkdb.sh
  - /var/www/uguu/src/static/scripts/checkfiles.sh
  
- name: copy systemd timer files
  template:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
  with_items:
  - check_files_db.service
  - check_files_db.timer
  notify:
  - restart systemd timer
  
- name: copy uguu.conf file
  template:
    src: uguu.conf
    dest: /etc/nginx/conf.d/uguu.conf
  notify:
  - nginx restart

- name: change post_max_size in php.ini file
  replace:
    path: /etc/php/8.0/fpm/php.ini
    regexp: 'post_max_size = .*'
    replace: post_max_size = {{ max_upload_size }}M

- name: change upload_max_size in php.ini file
  replace:
    path: /etc/php/8.0/fpm/php.ini
    regexp: 'upload_max_filesize = .*'
    replace: upload_max_filesize = {{ max_upload_size }}M

- name: set checkfile.sh path
  replace:
    path: /var/www/uguu/src/static/scripts/checkfiles.sh
    regexp: '/path/to/files/'
    replace: /var/www/files/

- name: replace rm command to srm commd in checkfile.sh 
  replace:
    path: /var/www/uguu/src/static/scripts/checkfiles.sh
    regexp: 'rm -f'
    replace: srm -z
  
- name: set checkdb.sh path
  replace:
    path: /var/www/uguu/src/static/scripts/checkdb.sh
    regexp: '/path/to/db/uguu.sq3'
    replace: /var/www/db/uguu.sq3

- name: replace config.json template
  template:
    src: config.json.j2
    dest: /var/www/uguu/src/config.json

# - name: Build the default target
#   community.general.make:
#     chdir: /var/www/uguu/
#   become: yes
  
# - name: Run 'install' target as root
#   community.general.make:
#     chdir: /var/www/uguu/
#     target: install
#   become: yes
  
- name: restart php-fpm
  systemd:
    name: php8.0-fpm
    state: restarted
    enabled: yes
...