---
# handlers file for ansible-role-uguu
- name: nginx restart
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: restart systemd timer
  systemd:
    name: check_files_db.timer
    state: restarted
    enabled: yes
    daemon_reload: yes
  